language: node_js

node_js:
  - "6"

sudo: false

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh

script:
  - yarn run lint

before_deploy:
  - yarn run build
  - cp ./dist/index.html ./dist/200.html

deploy:
  provider: surge
  project: ./dist/
  domain: vue-foursquare.surge.sh
  skip_cleanup: true
